### ISSUE TITLE
Pretrained weights can not be downloaded! help me 

### ISSUE THREAD

**Issue by dlthfyd138** [javirk/Person-remover-partial-convolutions#1]
I sincerely want to use your source code. But I can't get pretrained weights. What should I do? help me please

**Comment by javirk** [comment]
Hi, pretrained weights for partial convolutions model are in https://drive.google.com/file/d/12Y9OzZjw6yTPPLqhBMEnBn1r4I_83UIC/view. The link works fine for me.

**Comment by dlthfyd138** [comment]
thank for  your reply really
but My problem is /detector/weights 's Pretrained Weight 
http://sceneparsing.csail.mit.edu/model/pytorch/ : this link are break

**Comment by dlthfyd138** [comment]
> 
> 
> Hi, pretrained weights for partial convolutions model are in https://drive.google.com/file/d/12Y9OzZjw6yTPPLqhBMEnBn1r4I_83UIC/view. The link works fine for me.

thank for your reply really
but My problem is /detector/weights 's Pretrained Weight
http://sceneparsing.csail.mit.edu/model/pytorch/ : this link are break

**Comment by dlthfyd138** [comment]
Thanks your code. once againt

but when i run the code.

I get the following error.

How can I solve this??

I appreciate your code once again and I really want to use it
[image: 화면 캡처 2021-05-11 002150.jpg]

2021년 5월 10일 (월) 오전 2:27, Javier Gamazo ***@***.***>님이 작성:
